workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.peatrack.peat_tracker
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app